### ISSUE TITLE
Στην αρχική σελίδα (λίστα θεμάτων) θα πρέπει να μην βλέπουμε ολόκληρη την φόρμα αλλά μόνο τον τίτλο της και το read-more.

### ISSUE THREAD

**Issue by plirof2** [itminedu/forms_minedu#3]
Στην αρχική σελίδα (λίστα θεμάτων) θα πρέπει να μην βλέπουμε ολόκληρη την φόρμα αλλά μόνο τον τίτλο της και το read-more.

**Comment by plirof2** [comment]
Δοκιμάστηκε το `Read More link module` και δεν φάνηκε να λύνει το πρόβλημα. Εμφάνιζε το link read more αμέσως μετά τον τίτλο αλλά δεν έκρυβε την φόρμα.

**Comment by giannisdag** [comment]
Διορθώθηκε με προσθήκη subtheme, και αλλαγή στο node.tpl
